- src/lib/opencga/variant/variant-browser-filter.html
- src/lib/opencga/variant/variant-browser-grid.html
- src/lib/opencga/variant/variant-browser-view.html
Inline documentation added to the Variant browser filters and variant browser grid
> Next v2.0.0

- src/lib/opencga/variant/variant-browser-filter.html
> Web: new section PanelApp in variant browser filter

- src/webcomponents/clinical/clinical-analysis-grid.js
> wc: minor style fix

- package.json
- rollup.config.js
This PR fixes the error in the build process that was caused by an updated dependency.
> TASK-545: Fix jsorolla build

- src/webcomponents/variant/interpretation/variant-interpreter-browser-toolbar.js
This PR introduces some improvements in the Variant Interpreter tool.
> TASK-476 - Variant Interpreter improvements

- package.json
- rollup.config.js
- src/sites/iva/iva-app.js
- src/webcomponents/commons/layouts/custom-footer.js
- vite.config.js
This PR fixes the version displayed in the footer section of the IVA App.
> TASK-576 - Displayed version in IVA should be extracted from package.json

- src/webcomponents/disease-panel/disease-panel-browser.js
> TASK-601 - Fix Rest Call genes.name to genes.id

- src/webcomponents/sample/sample-cancer-variant-stats-plots.js
This PR sets the default region filter of the QC plots section to the canonical chromosomes.
> TASK-628 - Chromosome filter in QC section

- src/webcomponents/api/rest-endpoint.js
This PR fixes the rest-api "defaultValue" boolean problem.
> TASK-604 - In REST API app boolean values are checked by default but a false value is sent in the request

- src/webcomponents/cohort/cohort-detail.js
- src/webcomponents/disease-panel/disease-panel-detail.js
- src/webcomponents/file/opencga-file-detail.js
- src/webcomponents/individual/individual-detail.js
- src/webcomponents/sample/sample-detail.js
This PR fixes the details tab from browser
> TASK-600 - Review that the detail sections in all browsers 

- src/webcomponents/clinical/opencga-clinical-review-cases.js
- src/webcomponents/commons/filters/disorder-id-families-autocomplete.js
- src/webcomponents/commons/filters/disorder-id-individuals-autocomplete.js
- src/webcomponents/disease-panel/disease-panel-browser-filter.js
- src/webcomponents/family/opencga-family-filter.js
- src/webcomponents/individual/individual-browser-filter.js
This PR resolved component `disorder-id` & `disorder-automplete`
> wc: changed component 'disorder-id-*' to 'disorder-autocomplete'

- src/webcomponents/gene/gene-grid.js
This PR display the number of pagination.
> TASK-599 - Improving disease panel detail tab grids: display the number of elements returned in bold

- src/webcomponents/family/opencga-family-browser.js
This PR fixes a typo in Disorder filter name.
> typo fixed #498

- src/webcomponents/variant/interpretation/variant-interpreter-browser-template.js
- src/webcomponents/variant/interpretation/variant-interpreter-grid.js
- src/webcomponents/variant/interpretation/variant-interpreter-rearrangement-grid.js
- src/webcomponents/variant/variant-browser-filter.js
- src/webcomponents/variant/variant-browser-grid.js
- src/webcomponents/variant/variant-browser.js
This PR allows disabling the Search button while the query is being executed in the Variant Browser and the Variant Interpreter Browser.
> TASK-657 - Disable Search button in the Variant Interpreter and Variant Browser

- src/core/clients/opencga/opencga-parent-class.js
- src/core/clients/rest-client.js
- src/webcomponents/file/file-preview.js
After enabling again `generateKey` in OpenCGA client, some new developments like the new Case Portal stopped working. This PR disables the `gelerateKey` in the OpenCGA client.
> TASK-670 - Disable generateKey in OpenCGA client

- src/webcomponents/commons/forms/data-form.js
This PR resolved element not vertically aligned
> TASK-339 - Default values for attributes not vertically aligned in the case creation form

- src/webcomponents/commons/filters/phenotype-name-autocomplete.js
- src/webcomponents/family/opencga-family-filter.js
- src/webcomponents/individual/individual-browser-filter.js
This PR resolved phenotype autocomplete for individual & family filters
> TASK-678: IVA family browser does not have autocomplete for phenotype filter

- src/webcomponents/cohort/cohort-create.js
- src/webcomponents/cohort/cohort-update.js
- src/webcomponents/cohort/cohort-view.js
- src/webcomponents/family/family-create.js
- src/webcomponents/family/family-update.js
- src/webcomponents/individual/individual-create.js
- src/webcomponents/individual/individual-update.js
- src/webcomponents/sample/sample-create.js
- src/webcomponents/sample/sample-update.js
This PR resolved phenotypes and disorders
> TASK-783: Update Individual phenotypes and disorders not working

- src/webcomponents/clinical/clinical-analysis-browser.js
This PR solves the problem presented in the clinical browser.
> TASK-800: Sometimes the clinical browser crashes

- src/webcomponents/clinical/clinical-analysis-grid.js
- src/webcomponents/clinical/clinical-analysis-group.js
This PR fixes some defects detected in the new Case Portal.
> TASK-358 - Implement new Case Portal [Defects fixes]

- src/webcomponents/variant/interpretation/variant-interpreter-review-primary.js
- src/webcomponents/variant/interpretation/variant-interpreter-review.js
- src/webcomponents/variant/interpretation/variant-interpreter.js
This PR fixes a bug in the Variant Interpretation Review for displaying the Copy option in the variant grid of this view.
> TASK-711 - Add EPIC copy option to Interpretation Review

- src/webcomponents/clinical/clinical-analysis-manager.js
- src/webcomponents/clinical/interpretation/clinical-interpretation-manager.js
- src/webcomponents/variant/interpretation/variant-interpreter-browser-template.js
- src/webcomponents/variant/interpretation/variant-interpreter-review-primary.js
This PR allowed lock/unlock interpretation
> TASK-806: Allow to lock an interpretation in IVA interpretation manager

- src/webcomponents/variant/interpretation/variant-interpreter-grid-config.js
This PR fixes the location of the CellBase configuration for the current project in the variant grid config component.
> TASK-945 - Transcript filter missing options

- src/genome-browser/demo/examples/features-of-interest.js
- src/genome-browser/demo/genome-browser-opencga.html
- src/genome-browser/demo/genome-browser.html
- src/genome-browser/genome-browser-styles.css
- src/genome-browser/genome-browser.js
- src/genome-browser/panels/chromosome-panel.js
- src/genome-browser/panels/karyotype-panel.js
- src/genome-browser/panels/navigation-bar.js
- src/webcomponents/variant/interpretation/variant-interpreter-browser.js
This PR implements the features of interest requirement that allows providing a list of regions to highlight in Genome Browser.
> TASK-590 - Add features of interest in Genome Browser

- src/webcomponents/clinical/clinical-analysis-create.js
This PR fixes a bug in the create case form that after creating the case the due date is not cleared.
> TASK-340 - Due-date is not cleared after submitting a case

- src/webcomponents/job/opencga-job-detail-log.js
This PR resolved warning job status
> TASK-611 - Job browser warning for pending jobs not able to display stderr log

- src/core/notification-manager.js
- src/sites/api/api-app.js
- src/sites/iva/iva-app.js
- src/webcomponents/clinical/clinical-analysis-grid.js
- src/webcomponents/commons/list-update.js
- src/webcomponents/commons/opencga-active-filters.js
- src/webcomponents/commons/utils/notification-utils.js
- src/webcomponents/sample/sample-create.js
- src/webcomponents/study/admin/study-admin-users.js
- src/webcomponents/study/annotationset/annotation-set-update.js
- src/webcomponents/study/variable/variable-set-create.js
- src/webcomponents/study/variable/variable-set-update.js
- src/webcomponents/variant/variant-browser-grid.js
This PR adds a confirmation notification to replace SWAL in IVA.
> TASK-351 - Create a confirmation notification

- src/webcomponents/variant/interpretation/variant-interpreter-browser.js
- src/webcomponents/visualization/genome-browser.js
This PR fixes a bug in the Genome Browser component that caused that the webcomponent was not listening for configuration or tracks changes.
> TASK-992 - Primary Findings are not updated in the features of interest dropdown of Genome Browser

- src/webcomponents/variant/interpretation/case-steiner-report.js
This PR adds the Small deletions and insertions count plot in the report.
> TASK-1098 - Include small deletions and insertions count plot in report

- src/webcomponents/commons/view/detail-tabs.js
- src/webcomponents/variant/interpretation/variant-interpreter-browser.js
- src/webcomponents/variant/interpretation/variant-interpreter-grid.js
This PR adds a new link in the Action dropdown to open the current variant region in the Genome Browser tab.
> TASK-1107 - Add variant link to Genome Browser

- src/webcomponents/job/opencga-job-detail-log.js
This PR adds the `QUEUED` status to the list of job statuses without logs.
> TASK-1259 - CatalogException Cannot see stderr log file of job with status 'QUEUED'.

- src/sites/api/api-app.js
- src/sites/iva/iva-app.js
This PR fixes a race condition when creating the OpenCGA session and verifying the token when IVA starts, that is causing the annoying message `No valid token:null`.
> TASK-1268 - IVA: No valid token : null

- src/webcomponents/variant/interpretation/variant-interpreter-grid.js
This PR fixed dropdown variant-browser-interpreter
> TASK-974 - Action dropdown in variant grid component in the last rows becomes hidden when it is beyond the table limits

- src/core/utilsNew.js
- src/webcomponents/commons/opencga-browser-filter.js
This PR prevents displaying the filters section empty when in the configuration there is a filter that does not exist in the available filters list.
> TASK-1207 - Filter section is not displayed in case portal view in customers with IVA 2.4.x

- src/webcomponents/commons/filters/cadd-filter.js
- src/webcomponents/commons/filters/protein-substitution-score-filter.js
This PR fixed ranges for deleterious filters
> TASK-1269 - VB deleterious filters ranges need to be limited in the score input area (SIFT, Polyphen and CADD)

- src/sites/iva/iva-app.js
- src/webcomponents/file/file-manager.js
This PR fixes a bug in the file manager that does not clear the previous file content when a new folder is selected.
> TASK-1364 - File Explorer does not clear the file info section when opening a folder

- src/webcomponents/clinical/clinical-analysis-create.js
- src/webcomponents/commons/forms/data-form.js
This PR resolves the warning about new changes
> TASK-1256 - The warning about new changes not been saved should not be shown before starting to edit the "create case" form.

- src/webcomponents/sample/sample-cancer-variant-stats-browser.js
This PR adds the Search button back in the Cancer QC browser.
> TASK-1417 - Missing search button in QC

- src/webcomponents/variant/interpretation/case-steiner-report.js
This PR fixes the custom filtering section of the report.
> TASK-1416 - Fill custom filtering section in report

- src/webcomponents/commons/filters/disorder-autocomplete.js
- src/webcomponents/commons/filters/phenotype-name-autocomplete.js
This PR restricts values returned in the phenotypes and disorders filters.
> TASK-1502 - Individual Browser phenotype and disease filters: search does not restring results

- src/webcomponents/variant/interpretation/variant-interpreter-browser-template.js
This PR resolved clear filter action
> TASK-1465 - Clear filter action clears disabled filters too

- src/webcomponents/clinical/interpretation/clinical-interpretation-variant-review.js
This PR displays comments author and date in the variant review modal.
> TASK-1541 - Show author and date in variant comments

- src/webcomponents/disease-panel/disease-panel-summary.js
- src/webcomponents/family/family-view.js
- src/webcomponents/individual/individual-view.js
This PR resolved disorders from individual-view, family-view and disease-panel-summary
> TASK-1526 - In individual browser disorders are not correctly rendered

- src/webcomponents/clinical/interpretation/clinical-interpretation-variant-review.js
This PR adds the author and date fields to each new comment added in the variant review modal.
> TASK-1473 - Review variant comments don't show who and when were written

- src/webcomponents/clinical/clinical-analysis-comment-editor.js
- src/webcomponents/clinical/clinical-analysis-review.js
- src/webcomponents/clinical/interpretation/clinical-interpretation-variant-evidence-review.js
- src/webcomponents/clinical/interpretation/clinical-interpretation-variant-review.js
- src/webcomponents/commons/forms/form-utils.js
This PR displays the author and date in all discussion boxes and fixes the data model for discussions.
> TASK-1531 - Show Author and Date in Discussion Box.

- src/webcomponents/commons/filters/catalog-search-autocomplete.js
- src/webcomponents/commons/forms/select-token-filter.js
- src/webcomponents/commons/opencga-browser-filter.js
This PR resolved filter by file or directory
> TASK-1522 - File browser search filter by file or directory does not work

- src/webcomponents/variant/interpretation/variant-interpreter-grid.js
- src/webcomponents/variant/interpretation/variant-interpreter-review-primary.js
This PR allows unselecting variants from the Interpretation review.
> TASK-1534 - Cannot unselect variants from Interpretation Review

- src/webcomponents/clinical/rga/rga-browser.js
- src/webcomponents/clinical/rga/rga-gene-view.js
- src/webcomponents/clinical/rga/rga-individual-family.js
- src/webcomponents/clinical/rga/rga-individual-view.js
- src/webcomponents/clinical/rga/rga-variant-individual.js
- src/webcomponents/clinical/rga/rga-variant-view.js
- src/webcomponents/variant/variant-grid-formatter.js
This PR includes the following in RGA components:
- add supports to **DELETION_OVERLAP** knockout type
- remove tooltip about individuals not visible due to user permission
- minor bugfixes
> Rga bugfix

- src/webcomponents/commons/opencga-export.js
This PR fixes the export in the Sample Variant Browser.
> TASK-1400 - Export Query is not working in Sample Variant Browser

- src/webcomponents/clinical/clinical-analysis-view.js
This PR fixes how flags are displayed in the clinical analysis view.
> TASK-1552 - Flags are not correctly displayed in clinical analysis view

- src/webcomponents/commons/filters/variant-file-info-filter.js
This PR fixes filtering by categorical caller fields in Sample Variant Browser.
> TASK-1458 - Error when filtering by type in rearrangement browser

- src/webcomponents/variant/interpretation/variant-interpreter-browser-toolbar.js
This PR resolved button disabled.
> TASK-1560 - The dialog buttons inside the action buttons in Sample Variant Browser performs an action even if they are disabled

- src/webcomponents/sample/sample-variant-stats-browser.js
This PR adds the Run button to the Somatic and Germline Variant Stats browser.
> TASK-1622 - Run button is missing in Somatic and Germline Variant stats

- src/webcomponents/alignment/gene-coverage-detail.js
- src/webcomponents/api/rest-endpoint.js
- src/webcomponents/clinical/clinical-analysis-detail.js
- src/webcomponents/cohort/cohort-detail.js
- src/webcomponents/commons/view/detail-tabs.js
- src/webcomponents/disease-panel/disease-panel-detail.js
- src/webcomponents/family/family-detail.js
- src/webcomponents/file/file-browser.js
- src/webcomponents/file/file-detail.js
- src/webcomponents/file/file-filter.js
- src/webcomponents/file/file-grid.js
- src/webcomponents/individual/individual-detail.js
- src/webcomponents/job/job-detail.js
- src/webcomponents/sample/sample-browser.js
- src/webcomponents/sample/sample-detail.js
- src/webcomponents/study/admin/study-admin-cohort.js
- src/webcomponents/study/admin/study-admin-configuration.js
- src/webcomponents/study/admin/study-admin-family.js
- src/webcomponents/study/admin/study-admin-individual.js
- src/webcomponents/study/admin/study-admin-sample.js
- src/webcomponents/study/admin/study-admin-variable.js
- src/webcomponents/user/user-profile.js
- src/webcomponents/variant/analysis/opencga-knockout-analysis/knockout-variant-view.js
- src/webcomponents/variant/interpretation/variant-interpreter-detail.js
- src/webcomponents/variant/variant-browser-detail.js
This PR resolved detail tabs when is empty
> TASK-1600 - Browser:  When results are empty

- src/core/utilsNew.js
- src/webcomponents/commons/simple-chart.js
- src/webcomponents/file/file-preview.js
- src/webcomponents/sample/sample-cancer-variant-stats-browser.js
- src/webcomponents/sample/sample-cancer-variant-stats-plots.js
- src/webcomponents/variant/interpretation/case-steiner-report.js
This PR fixes the plots displayed in the report.
> TASK-1368 - Plots in report must comply with QC filters

- src/webcomponents/variant/interpretation/variant-interpreter-grid.js
This PR renames and fixes the columns in the variant-interpreter-grid.
> TASK-1243 - Rename columns

- src/webcomponents/variant/variant-grid-formatter.js
This PR sets a maximum width to the discussion column in the reported cases table.
> TASK-1691 - Limit the width of the discussion column in the Reported Cases section of SVB

- src/webcomponents/file/file-grid.js
This PR fixes a bug in the file grid when the user tries to hide the directory column.
> TASK-1661 - File browser hide column directory does not work.

- src/webcomponents/commons/opencga-browser-filter.js
This PR fixes the annotation filter in all catalog browsers.
> TASK-1660 - File browser display a File Annotation filter but is void.

- src/webcomponents/commons/opencga-export.js
This PR fixes exporting in VCF and VEP formats from `opencga-export` component.
> TASK-1794 - Export query for variant analysis and clinical analysis does not add the output-file-format to the exports, always exporting to VCF

- src/webcomponents/variant/annotation/cellbase-population-frequency-grid.js
This PR fixes the Population Frequency plot for displaying all legend labels.
> TASK-1724 - Pop. frequency bar plot does not show values for all populations

- src/webcomponents/clinical/interpretation/clinical-interpretation-variant-evidence-review.js
This PR fixes saving ACMG comments in the variant evidence review component.
> TASK-1870 - Issues when creating new ACMG items in the Review Variant Evidence menu (Sample Variant Browser)

- src/genome-browser/css/genome-browser.css
- src/genome-browser/panels/navigation-bar.js
This PR fixes the position and the order of the buttons and inputs in the navigation panel of Genome Browser.
> TASK-1233 - Fix buttons in Navbar panel of Genome Browser

- src/webcomponents/cohort/cohort-browser.js
This PR fixes a bug displaying the samples of a cohort when the cohort has a large number of samples associated.
> TASK-1906 - Details tab Sample (Cohort Browser) shows Error when trying to display information from the /samples/search endpoint

- src/webcomponents/api/rest-endpoint.js
This PR adds the query params to the url for the API REST POST methods
> TASK-1939 - IVA REST-API tool for families create  does not pass the family members to the REST call

- src/webcomponents/commons/opencga-active-filters.js
- src/webcomponents/variant/interpretation/variant-interpreter-browser-cancer.js
- src/webcomponents/variant/interpretation/variant-interpreter-browser-cnv.js
- src/webcomponents/variant/interpretation/variant-interpreter-browser-rd.js
- src/webcomponents/variant/interpretation/variant-interpreter-browser-rearrangement.js
This PR fixes some UI issues in the active filters dropdown menu.
> TASK-2004 - UI issues in active filters menu

- src/webcomponents/clinical/rga/rga-filter.js
- src/webcomponents/commons/filters/population-frequency-filter.js
This PR includes the following fix:
- Checkbox added in `population-frequency-filter` to query for absent variants in DBs. KMDS-1402.
> Rga bugfix KMDS-1402.

- src/core/bioinfo/bioinfo-utils.js
- src/webcomponents/variant/interpretation/variant-interpreter-grid.js
- src/webcomponents/variant/variant-grid-formatter.js
This PR includes an external link to DECIPHER for each variant
> TASK-1164 - Include an external link to DECIPHER for each variant

- src/core/notification-manager.js
This PR fixes a bug in the NotificationsManager and allows to display results events from response.
> TASK-2053 - Notifications are not displaying results events

- src/webcomponents/clinical/rga/rga-gene-view.js
- src/webcomponents/clinical/rga/rga-individual-family.js
- src/webcomponents/clinical/rga/rga-individual-view.js
- src/webcomponents/clinical/rga/rga-variant-individual.js
- src/webcomponents/clinical/rga/rga-variant-view.js
This PR resolves the following issue:
- Replacing numCompHet with numPairedCompHet in variantStats. KMDS-1446
- Fixing download functions in RGA. KMDS-1453
- Replacing DELETION_OVERLAP with COMP_HET. KMDS-1407
> Rga bugfixes

- src/core/bioinfo/bioinfo-utils.js
- src/webcomponents/variant/interpretation/variant-interpreter-grid-formatter.js
- src/webcomponents/variant/variant-grid-formatter.js
This PR fixes a link to Sequence Ontology in Variant Browser.
> TASK-2093 - Link to sequenceontology not working

- src/webcomponents/job/job-view.js
> TASK-2116 - Job view displays output files without names

- src/webcomponents/commons/opencga-active-filters.js
Style fixes in active filters.
> TASK-2078 - Style issues in active filters buttons

- src/webcomponents/variant/variant-grid-formatter.js
This PR fixes the label width of the Population Frequencies tooltip.
> TASK-2079 - Fix text wrap in population frequencies tooltip

- src/webcomponents/clinical/rga/rga-gene-view.js
- src/webcomponents/clinical/rga/rga-individual-family.js
- src/webcomponents/clinical/rga/rga-individual-view.js
- src/webcomponents/clinical/rga/rga-variant-allele-pairs.js
- src/webcomponents/clinical/rga/rga-variant-view.js
- styles/css/global.css
This PR includes the following changes:
- Fixing Text Alignment to center in Table headers. KMDS-1519
- Allele Pair Table refactor. KMDS-1301
- Sort results in Variant view in case results < pageSize. KMDS-1391
> Rga improvements

- src/webcomponents/commons/filters/conservation-filter.js
This PR resolved conservation filter issue
> TASK-2192 - PhastCons and GERP values disappear from the filter menu after clicking search in the Sample Variant Browser and Variant Browser

- src/webcomponents/study/admin/study-admin-users.js
This PR fix the problem of adding/removing a user from an existing group.
> TASK-2042 - IVA `TypeError` in Study_Admin:users_and_groups view when clicking in checkbox at groups column

- src/core/clients/opencga/opencga-catalog-utils.js
- src/core/clients/opencga/opencga-client.js
This PR fixes a bug saving the list of acls of a study.
> TASK-2228 - Clinical Analysis Grid displays a TypeError when using demouser

- src/webcomponents/individual/individual-grid.js
This PR fixes the `sex` column in the downloaded TAB file from the Interpreter browser.
> TASK-2190 - Download Tab format (Individual Browser) displays the sex information as [object Object]

- src/webcomponents/clinical/interpretation/clinical-interpretation-variant-evidence-review.js
This PR fixes clearing the Clinical Significance field in the evidences review modal.
> TASK-2193 - Sample Variant Browser - Remove/clear ACMG Classification in Review Variant Evidence Issue

- src/webcomponents/clinical/clinical-analysis-update.js
- src/webcomponents/commons/forms/data-form.js
- src/webcomponents/variant/interpretation/variant-interpreter-landing.js
- src/webcomponents/variant/interpretation/variant-interpreter.js
This PR fix the problem of locking a case or a panel without saving, and see applied changes in the variant browser
> TASK-2209 - Disease Panel Lock and Case Lock can be applied to a clinical case without saving the changes in the Case Manager

- src/webcomponents/clinical/clinical-analysis-update.js
- src/webcomponents/clinical/interpretation/clinical-interpretation-update.js
This PR fixes the displayed author and date in new comments of the `clinical-analysis-update` and the `clinical-interpretation-update`.
> TASK-2232 - When adding New Comments, the user and the date are not displayed until the changes are saved

- src/webcomponents/variant/interpretation/variant-interpreter-browser-toolbar.js
- styles/css/global.css
This PR fixes the overflowing text in sample variant view and inclusion variants
> TASK-2268 - Text for variant ids needs proper wrapping in Sample Variant Browser  view button display

- src/webcomponents/commons/filters/variant-file-info-filter.js
This PR fixes the Variant Caller File Filter.
> TASK-2319 - IVA Variant Caller File Filter dropdown always set the value to PASS

- src/webcomponents/cohort/cohort-browser.js
This PR sets a more appropriate label in Cohort ID filter
> TASK-2317 - Cohort Browser - IVA label ID in filter not accurate enough and leads to confusion

- src/webcomponents/commons/filters/variant-file-info-filter.js
This PR fixes adding the comparator to categorical values in the Variant Caller File Info Filter component.
> TASK-2322 - Variant Caller File Info Filter removes the '=' comparator from the fileData query

- src/webcomponents/api/rest-api.js
This PR removed the file/upload endpoint from Api
> TASK-2202 - Input area missing for files/upload IVA REST API

- src/core/utils-new.js
- src/webcomponents/commons/forms/select-token-filter.js
- src/webcomponents/commons/opencga-active-filters.js
- src/webcomponents/commons/opencga-browser.js
- src/webcomponents/individual/individual-browser.js
This PR allows using regex as separator for select-token-filter
> TASK-2255 - The disorder filter splits the disorder.name strings by commas

- src/webcomponents/cohort/cohort-browser.js
- src/webcomponents/commons/filters/catalog-distinct-autocomplete.js
- src/webcomponents/commons/opencga-browser-filter.js
This PR fixes the cohort browser type filter for displaying the list of available terms
> TASK-2318 - Cohort Browser - Type filter is not displaying the list of applicable terms for querying

- src/sites/iva/conf/clinical-analysis-portal.settings.js
- src/sites/iva/conf/opencga-clinical-review-cases.settings.js
- src/webcomponents/clinical/clinical-analysis-grid.js
This PR fixes de export download in case portal
> TASK-2320 - Case Portal export download button produces no action in EGLH

- src/webcomponents/variant/interpretation/case-steiner-report.js
- src/webcomponents/variant/interpretation/variant-interpreter.js
This PR fixes a bug in the case-steiner report dislaying the Germline SNV variants.
> TASK-2326 - Germline SNVs not showing in report

- src/webcomponents/variant/interpretation/variant-interpreter-browser.js
This PR fixes opening a region in the Genome Browser of the Sample Variant Browser.
> TASK-2323 - Action link to genome browser does not take to the right position

- src/sites/iva/conf/opencga-variant-constants.js
- src/webcomponents/variant/interpretation/variant-interpreter-grid-formatter.js
- src/webcomponents/variant/interpretation/variant-interpreter-grid.js
- src/webcomponents/variant/variant-browser-grid.js
- src/webcomponents/variant/variant-grid-formatter.js
- styles/css/global.css
This PR adds the gnomAD Exomes to population frequencies and displays the counts in the population frequencies tooltip.
> TASK-2287 - Het + Hom count in gnomAD

- src/webcomponents/commons/view/signature-view.js
- src/webcomponents/variant/interpretation/case-steiner-report.js
This PR fixes a bug in the report component when displaying signatures plots.
> TASK-2500 - Bug displaying signature plots in report

- src/webcomponents/clinical/analysis/mutational-signature-analysis.js
This PR prevents running the mutational signature analysis when the fitting ID already exists.
> TASK-2499 - Fittting IDs must be unique

- src/webcomponents/clinical/clinical-analysis-create.js
This PR solves the defect of adding comments in clinical analysis create
> TASK-2585 - Adding a comment in a case creation form disables form buttons functionality

- src/webcomponents/study/admin/catalog-admin.js
- src/webcomponents/study/admin/study-admin.js
- src/webcomponents/study/admin/variant/study-variant-admin.js
This PR fixes the absolute import of the `custom-vertical-navbar` component.
> TASK-2592 - Fix absolute import of custom-vertical-navbar component

- src/core/utils-new.js
- src/webcomponents/variant/interpretation/variant-interpreter-grid.js
This PR added new functionality to dialog modal
> TASK-2524 - implement draggable modal

- src/webcomponents/individual/qc/individual-qc-mendelian-errors.js
- src/webcomponents/variant/interpretation/variant-interpreter-qc-mendelian-errors.js
This PR fixes a bug in the QC Overview section displaying the mendelian errors view.
> TASK-2490 - Mendelian error section doesn't display any results (QC interface)

- src/webcomponents/variant/variant-grid-formatter.js
This PR allows to use the client-tailored acronym for clinical significance
> TASK-2398 - EGLH: Enable customers to configure the ClinVar column

- src/webcomponents/commons/filters/individual-hpo-filter.js
- src/webcomponents/variant/variant-browser-filter.js
This PR fixes a defect with the HPO filter.
> TASK-3915 - HPO's patient filter

- .github/workflows/develop.yml
- .github/workflows/release.yml
- .github/workflows/task.yml
- package.json
This PR fixes the version of the `bootstrap-table` dependency in `package.json`.
> TASK-4062 - Error installing the latest version of bootstrap-table

- src/webcomponents/variant/interpretation/variant-interpreter-browser-cancer.js
- src/webcomponents/variant/interpretation/variant-interpreter-browser-cnv.js
- src/webcomponents/variant/interpretation/variant-interpreter-browser-rd.js
- src/webcomponents/variant/interpretation/variant-interpreter-browser-rearrangement.js
- src/webcomponents/variant/interpretation/variant-interpreter-browser-template.js
This PR fixes the query reset when changing the browser tab in Sample Variant Browser.
> TASK-3962 - Filters are cleared out when changing tabs in sample variant browser

- src/webcomponents/variant/interpretation/variant-interpreter-grid.js
- src/webcomponents/variant/interpretation/variant-interpreter-review.js
This PR fixes the grids displayed in `variant-interpreter-review`.
> TASK-2325 - Missing variant types in interpretation review

- package.json
- src/webcomponents/variant/interpretation/variant-interpreter-qc-summary.js
This PR fixes the message displayed at the quality control summary when no disorders are associated to the case
> TASK-2443 - Quality Control interface shows Error:No valid data found in the Disorder field

- src/webcomponents/commons/grid-commons.js
- src/webcomponents/variant/interpretation/variant-interpreter-grid-formatter.js
- src/webcomponents/variant/interpretation/variant-interpreter-grid.js
This PR fixes the `show more genes` link in the Genes column of Variant Browser.
> TASK-2434 - The ' Show more genes' link in Variant Browser does not display more genes

- src/webcomponents/clinical/analysis/exomiser-analysis.js
This PR fixes the condition for displaying the warning message in the Exomiser analysis form.
> TASK-4025 - Exomiser interface shows a message saying no phenotypes or disorders are associated with the individual when there are

- src/webcomponents/commons/analysis/analysis-utils.js
This PR allows to select genes using a dropdown in the analysis forms like in the variant browser filters.
> TASK-3999 - Gene input area in analysis Sample Variant Stats should have the gene selector active

- src/webcomponents/variant/variant-grid-formatter.js
This PR fixes displaying the number of cosmic studies in the Variant Browser Grid.
> TASK-4029 - Incorrect number of cosmic studies is shown in the Variant Browser table

- src/webcomponents/file/file-manager.js
- src/webcomponents/sample/sample-browser.js
- src/webcomponents/sample/sample-detail.js
This PR allows displaying VIRTUAL files in the Files tab of the Sample Browser.
> TASK-3894 - Virtual files not shown at sample associated files tab

- src/webcomponents/individual/qc/individual-qc-mendelian-errors.js
This PR implements the `onDownload` listener for the `individual-qc-mendelian-errors` component
> TASK-3767 - Download button of mendelian-errors component does not work

- src/webcomponents/variant/variant-utils.js
This PR resolved the export TSV acmg column
> TASK-2441 - Export TSV (Sample Variant Browser) outputs incorrect ACMG prediction values

- src/webcomponents/clinical/analysis/rd-tiering-analysis.js
This PR fixes a bug in the RD Tiering analysis.
> TASK-2504 - RD Tiering form in Case_Interpreter::Interpretation_Methods is not sent when pressing OK button

- src/webcomponents/opencga/opencga-gene-view.js
This PR solves the problem of displaying LoF variants only in Gene View
> TASK-2208 - Gene View interface doesn´t show LOF variants only

- .github/workflows/develop.yml
- .github/workflows/release.yml
- .github/workflows/task.yml
- package.json
- src/webcomponents/clinical/interpretation/clinical-interpretation-variant-review.js
This PR removes the possibility of adding comments in batches
> TASK-4018 - Adding comments in batches fails from the Review Variant menu (sample variant browser)

- src/webcomponents/clinical/interpretation/clinical-interpretation-variant-review.js
This PR solves the problem of adding comments to the clinical interpretation variant review
> TASK-3892 - Unable to add comments to Review Variants in sample variant browser

- src/webcomponents/variant/family-genotype-filter.js
This PR disables some Modes Of Inheritance in the `family-genotype-filter` component when the clinical analysis does not have any disorder.
> TASK-4028 - Sample/Family Genotypes filter doesn't apply all Inheritance Patterns

- src/core/clients/opencga/opencga-client.js
- src/sites/iva/conf/config.js
- src/sites/iva/iva-app.js
This PR solves the problem of being redirected to landing page on reloading certain pages.
> TASK-4274 - IVA remains in landing page on reloading

- .babelrc
- package.json
- rollup.config.js
This PR fixes the babel dependencies for building IVA.
> TASK-4512 - Error when building IVA

- .babelrc
- package.json
- rollup.config.js
This PR fixes the babel dependencies when building IVA.
> TASK-4512 - Error when building IVA (develop)

- src/webcomponents/api/rest-endpoint.js
This PR fix duplicate study params and capture default value from select input.
> TASK-2366 - IVA API DOC for sample, individual, cohort, family and file ACL produces wrong REST call

- src/webcomponents/api/rest-endpoint.js
This PR fix query params requested URL
> TASK-4057 - IVA REST API is not adding the query params to the requested URL

- src/webcomponents/api/rest-endpoint.js
> TASK-3841 - IVA REST_APIapp for /analysis/alignment/coverage/qc/geneCoverageStats/run is missing the field "genes"

- src/webcomponents/variant/interpretation/exomiser/variant-interpreter-exomiser-view.js
Fix exomiser tab in Sample Variant Browser.
> TASK-4490 - Exomiser Tab is empty in Sample Variant Browser

- src/webcomponents/clinical/clinical-analysis-create.js
This PR fixes the `clinical-analysis-create` when creating a family case.
> TASK-4573 - Family cases are created incorrectly from IVA

- src/webcomponents/variant/variant-browser-grid.js
This PR fixes the visibility of some columns in Variant Browser
> TASK-4496 - unable to hide cohorts and population columns in Variant analysis browser

- src/webcomponents/file/file-grid.js
This PR fix export JSON format data from file browser
> TASK-4014 File Browser- JSON format files do not show Sample IDs

- src/webcomponents/clinical/clinical-analysis-update.js
- src/webcomponents/commons/opencga-update.js
This PR disables the update and discard button in `clinical-analysis-update` when case is locked.
> TASK-4499 - The update button is active in the Case Manager in locked cases

- src/webcomponents/commons/analysis/analysis-utils.js
This PR improves the disease panels dropdown in all analysis forms.
> TASK-4503 - Disease panel selection issues in the Sample quality control analysis tool in IVA

- src/webcomponents/clinical/clinical-analysis-update.js
This PR fixes removing all disease panels in clinical analysis update.
> TASK-4504 - Disease Panels cannot be removed from a case via IVA

- src/webcomponents/variant/analysis/sample-qc-analysis.js
This PR fixes launching the Sample QC analysis.
> TASK-4683 - Unable to launch Sample QC analysis from IVA

- src/webcomponents/sample/sample-detail.js
This PR fixes a defect in the `develop` branch that causes an error in the generation of the build version of IVA.
> TASK-4845 - IVA Docker displays a blank screen

- cypress/e2e/iva/variant-browser-grid-cancer.cy.js
- cypress/e2e/iva/variant-browser-grid-germline.cy.js
- src/core/bioinfo/bioinfo-utils.js
- src/webcomponents/variant/interpretation/variant-interpreter-grid.js
- src/webcomponents/variant/variant-browser-grid.js
- src/webcomponents/variant/variant-grid-formatter.js
This PR adds Varsome links in variant browsers.
> TASK-3902 - Add gene and variant links to Varsome

- src/webcomponents/commons/grid-commons.js
- src/webcomponents/variant/interpretation/variant-interpreter-grid.js
- src/webcomponents/variant/variant-browser-grid.js
This PR solves the problem of non visible sub-columns when parent columns have been configured to be displayed by default
> TASK-4937 - Variant Browser - Ignored client settings in columns with sub-columns

- src/webcomponents/clinical/analysis/rd-tiering-analysis.js
This PR fixes the RD Tiering analysis form
> TASK-4868 - RD tiering analysis displays an empty Clinical Analysis ID

- src/webcomponents/commons/opencb-grid-toolbar.js
- src/webcomponents/job/job-grid.js
This PR fix the refresh job button missing in job browser
> TASK-5009 - IVA Job Browser - Refresh job button missing in Job Browser toolbar

- src/core/utils-new.js
- src/webcomponents/commons/layouts/custom-welcome.js
- src/webcomponents/user/user-login.js
This PR fixes a bug in the login screen.
> TASK-5271 - Landpage login error

- src/webcomponents/commons/forms/data-form.js
This PR fixes data-form to hide the modal when the form is submitted or discarded.
> TASK-5277 - Interpretation edit modal leaves disabled background on save

- src/webcomponents/clinical/clinical-analysis-create.js
- src/webcomponents/clinical/clinical-analysis-grid.js
- src/webcomponents/clinical/clinical-analysis-group.js
- src/webcomponents/clinical/clinical-analysis-review.js
- src/webcomponents/clinical/clinical-analysis-update.js
- src/webcomponents/clinical/clinical-analysis-view.js
- src/webcomponents/clinical/filters/clinical-analyst-filter.js
- src/webcomponents/clinical/interpretation/clinical-interpretation-create.js
- src/webcomponents/clinical/interpretation/clinical-interpretation-summary.js
- src/webcomponents/clinical/interpretation/clinical-interpretation-update.js
- src/webcomponents/cohort/cohort-update.js
- src/webcomponents/commons/opencga-update.js
- src/webcomponents/family/family-update.js
- src/webcomponents/individual/individual-update.js
- src/webcomponents/variant/custom/steiner-report.js
This PR solves the issues of changing the data model analysts to an array
> TASK-5374 - IVA create case does not work as TASK-5198 changed data-model

- src/webcomponents/clinical/clinical-analysis-group.js
This Pr enables the grouping by analyst in `clinical-analysis-group`.
> TASK-5396 - Fix group by array of analysts in Clinical Analysis Browser

- src/webcomponents/clinical/clinical-analysis-update.js
This PR fixes de problem of displaying udpated data in clinical analysis update
> TASK-5395 - Clinical Analysis Browser - Modal Update is not refreshing data after update

- src/webcomponents/variant/interpretation/variant-interpreter-landing.js
This PR fixes the access to the case interpreter update through the clinical analysis Id
> TASK-5408 - Case Interpreter Landing Manager - Case not available

- src/webcomponents/variant/interpretation/variant-interpreter-detail.js
This PR fixes displaying the genome browser in the rearrangement browser.
> TASK-5400 - Rearrangement genomic browsers do not appear in sample variant rearrangement browsers

- cypress/e2e/iva/genome-browser.cy.js
- src/genome-browser/panels/chromosome-panel.js
This PR fixes the cytobands labels order in Genome Browser.
> TASK-5067 - Cytoband notation is missplaced in genome browser

- src/sites/iva/iva-app.js
This PR fixes a routing issue when trying to access to a case using the url.
> TASK-5095 - IVA Routing issue

- package.json
TASK-5444 - Fix OpenCB repository versions to conform to XetaBase 2.0.0 version
> TASK-5444 - Fix OpenCB repository versions to conform to XetaBase 2.0.0 version

- src/webcomponents/variant/interpretation/variant-interpreter.js
This PR fixes a typo in the custom analysis of variant interpreter.
> TASK-5399 - Custom analysis section in case interpreter appears empty

- src/core/clients/cellbase/cellbase-client.js
- src/sites/iva/iva-app.js
- src/webcomponents/commons/layouts/custom-footer.js
This PR fixes de misplaced cellbase and opencga spinners when undefined
> TASK-5430 - CellBase text in footer and loading spinner missaligned  when cellbase host is not found

- src/webcomponents/clinical/clinical-analysis-create.js
This PR allows selecting a specific sample from the selected proband when creating a new Clinical Analysis.
> TASK-5094 - Unable to select specific samples for the proband when creating cases

- src/core/clients/opencga/opencga-client.js
- src/sites/iva/conf/config.js
- src/sites/iva/iva-app.js
This PR adds a new `cookie.secure` field to OpenCGA configuration in IVA to allow setting the secure flag in cookies.
> TASK-5487 - Allow IVA configuration for setting cookies in secure/insecure mode

- cypress/e2e/iva/variant-interpreter-grid-germline.cy.js
- src/core/bioinfo/bioinfo-utils.js
- src/webcomponents/variant/interpretation/variant-interpreter-grid.js
- src/webcomponents/variant/variant-browser-grid.js
- src/webcomponents/variant/variant-grid-formatter.js
This PR includes OMIM sub-column in Clinical Info column
> TASK-5653 - Include OMIM sub-column in Clinical Info colum

- src/webcomponents/variant/interpretation/variant-interpreter-grid.js
- src/webcomponents/variant/interpretation/variant-interpreter-rearrangement-grid.js
This PR fixes the query parameters used when exporting the query in SVB browsers.
> TASK-5647 - Export Query does not use the filters applied to the VB table

- src/webcomponents/commons/layouts/custom-landing.js
This PR fixes displaying the login form when SSO is enabled.
> TASK-4850 - Single Sign-On (SSO) authentication not working properly

- src/webcomponents/commons/forms/data-form.js
This PR fixes narrowed forms in IVA.
> TASK-5765 - Some forms in IVA are displayed narrowed

- src/core/bioinfo/bioinfo-utils.js
- src/webcomponents/variant/interpretation/variant-interpreter-grid.js
- src/webcomponents/variant/variant-browser-grid.js
This PR fixes the links to Cellbase in Variant Browser and Sample Variant Browser.
> TASK-5699 - Fix links to Cellbase in Variant Browser and Sample Variant Browser
