src/webcomponents/variant/interpretation/variant-interpreter-browser-cancer.js, src/webcomponents/variant/interpretation/variant-interpreter-browser-rearrangement.js
This PR fixes the default query generation of the rearrangements browser, so the `fileData` is added with the correct file.
=> TASK-509: Somatic and Germline Rearrangement browsers are displaying mixed variants

src/genome-browser/renderers/feature-renderer.js, src/genome-browser/renderers/gene-renderer.js
This PR fixes the duplicated features displayed in the Gene Overview Track of Genome Browser.
=> TASK-528 - Duplicated features in Gene Overview Track of GenomeBrowser

src/webcomponents/variant/interpretation/variant-interpreter-grid.js
This PR fixes the variant download in TSV in `variant-interpreter-grid.js`.
=> wc: variant-interpreter-grid TSV download fixed #479

src/core/clients/rest-client.js
This PR removes the hardcoded CellBase client name in the base `rest-client.js` module.
=> TASK-677 - OpenCGA REST client errors appear as "CellBase error"

src/webcomponents/commons/catalog-grid-formatter.js
This PR removes a trailing `/` in the panels URL.
=> TASK-739 - Malformed URL for panel app in disease panel column of case portal grid

src/webcomponents/variant/interpretation/variant-interpreter-review-primary.js, src/webcomponents/variant/interpretation/variant-interpreter-review.js
This PR fixes a bug in the variant interpretation review: user configuration is not merged into the grid default configuration.
=> TASK-862 - Transcript filter not filtering transcripts in Interpretation review

src/webcomponents/commons/utils/lit-utils.js
This PR fixes a bug in the `dispatchCustomEvent` that adds a `null` value to the dispatched event.
=> TASK-854 - UnrecognizedPropertyException in IVA: Export (Beta) -> Export Query -> Ensembl VEP.

src/genome-browser/panels/chromosome-panel.js
This PR displays the current chromosome name in the panel title section of the chromosome panel.
=> TASK-953 - Chromosome panel must display the current chromosome name in Genome Browser

src/webcomponents/variant/interpretation/variant-interpreter-browser.js
This PR fixes the displayed samples in the variant track when the case type is FAMILY.
=> TASK-977 - Genome Browser only displays the proband sample if the case type is family

src/genome-browser/genome-browser-utils.js, src/genome-browser/renderers/variant-renderer.js
This PR fixes the variant tooltip formatter for displaying the samples genotypes and depth.
=> TASK-940 - Sample genotypes and depth are not displayed in lollipop tooltip in Genome Browser

src/webcomponents/visualization/genome-browser.js
This PR fixes the initial NaN region in Genome Browser when there are no primary findings in the current interpretation.
=> TASK-983 - Genome Browser in SVB displays NaN region if there are no primary findings

src/webcomponents/variant/variant-utils.js
This PR fixes the SNP ID column name in the TSV export.
=> TASK-469 - SVB export variants TSV need all column names without spaces (join words with underscore)

src/webcomponents/variant/interpretation/variant-interpreter-grid.js, src/webcomponents/variant/variant-browser-grid.js
This PR fixes the variant interpreter grid to automatically select the row when the `+` icon is clicked (expand row).
=> TASK-1099 - Clicking on "+" must select the variant

src/genome-browser/genome-browser.js, src/genome-browser/panels/navigation-bar.js, src/webcomponents/commons/view/detail-tabs.js, src/webcomponents/variant/interpretation/variant-interpreter-browser-rearrangement.js, src/webcomponents/variant/interpretation/variant-interpreter-browser.js, src/webcomponents/variant/interpretation/variant-interpreter-detail.js, src/webcomponents/visualization/split-genome-browser.js
This PR adds a new component called `split-genome-browser` for visualizing multiple regions in different Genome Browsers instances at the same time, and uses this component for visualizing rearrangements in the Variant Rearrangement Browser.
=> TASK-1104 - Split screen on genome browser

src/webcomponents/job/opencga-job-detail-log.js
This PR fixes a typo in the logs detail of the Jobs Browser.
=> TASK-1360 - Typo in Job Browser Logs

src/genome-browser/genome-browser.js
This PR hides the panel container in Genome Browser when the panel is disabled in the configuration.
=> TASK-1228 - Panel container is still visible after disabling it in the configuration of Genome Browser.

src/genome-browser/tracks/opencga-variant-track.js, src/webcomponents/variant/interpretation/variant-interpreter-browser.js
This PR fixes a bug in the OpenCGA Variants track of Genome Browser that causes not all samples are visible by default on this track without scrolling.
=> TASK-1231 - Variant Track must display all samples without scrolling

src/genome-browser/genome-browser.js
This PR adds a fix for the Genome Browser: the detailed section is hidden and is never displayed.
=> TASK-1444 - Detailed section in Genome Browser is not visible

src/webcomponents/commons/view/detail-tabs.js
This PR fixes a bug in the `detail-tabs` component that hides all interpreter browsers when a tab in the detail section is changed.
=> TASK-1439 - Changing a tab in variant interpreter details hides all interpreter browsers

src/webcomponents/commons/opencga-export.js, styles/css/global.css
This PR removes the `ripple` class from export modal.
=> TASK-1419 - Export modal in Variant Browser is still using ripple buttons

src/webcomponents/commons/opencga-active-filters.js, src/webcomponents/variant/interpretation/variant-interpreter-browser-cancer.js, src/webcomponents/variant/interpretation/variant-interpreter-browser-cnv.js, src/webcomponents/variant/interpretation/variant-interpreter-browser-rd.js
This PR fixes the sample ID filter name in the `opencga-active-filters` component.
=> TASK-1533 - Wrong filter name when filtering by sample ID

src/webcomponents/variant/family-genotype-filter.js
This PR fixes the x-linked segregation mode in family-genotype-filter component.
=> TASK-1094 - Filter by X-linked segregation mode returns variants outside chrX

src/webcomponents/commons/filters/catalog-distinct-autocomplete.js, src/webcomponents/commons/forms/select-token-filter.js
This PR allows to restring search in catalog autocomplete filters like phenotype and disease filters.
=> TASK-1468 - Individual Browser phenotype and disease filters: search does not restring results

src/webcomponents/clinical/clinical-analysis-grid.js
This PR fixes the `Asigned To` field in the exported TSV from the clinical analysis grid.
=> TASK-1620 - 'Assigned To' field is empty when exporting clinical analysis

src/webcomponents/clinical/clinical-analysis-view.js
This PR fixes displaying the analyst Id in the clinical analysis view.
=> TASK-1590 - "Assign to" value is missing in case overview tabs

src/webcomponents/commons/view/detail-tabs.js, src/webcomponents/variant/interpretation/case-steiner-report.js, src/webcomponents/variant/interpretation/variant-interpreter-rearrangement-grid.js
This PR hides all settings buttons of the grids in the report view and merges the grid configuration with the user saved configuration used in the variant interpreter browser.
=> TASK-1461 - Settings in variant tables in report

src/webcomponents/variant/interpretation/variant-interpreter-browser-template.js, src/webcomponents/variant/interpretation/variant-interpreter-browser.js, src/webcomponents/variant/interpretation/variant-interpreter-grid.js, src/webcomponents/variant/interpretation/variant-interpreter-review-primary.js
This PR hides the GB link in the Actions dropdown of the variant interpreter grid when the GB tab is hidden in the variant interpreter browser.
=> TASK-1501 - GB link is still visible in the Actions menu after disabling GB in the interpretation settings

src/webcomponents/clinical/rga/rga-browser.js, src/webcomponents/clinical/rga/rga-individual-family.js, src/webcomponents/clinical/rga/rga-variant-individual.js, src/webcomponents/commons/opencga-active-filters.js
This PR addresses the following issues:
1. Renaming knockoutType in Recessive Genotype. KMDS-1293
2. Description tooltip added at numParents param. KMDS-1300
3. Gene View as a default View. KMDS-1303
=> Recessive Variant Browser improvements

src/webcomponents/variant/interpretation/variant-interpreter-rearrangement-grid.js
This PR fixes the displayed value in the Sample Genotypes column of the rearrangements grid component.
=> TASK-1762 - Fix headers in rearrangement browser

src/webcomponents/commons/opencga-export.js
This PR fixes the export types displayed in the export modal of the Sample Variant Browser.
=> TASK-1793 - The export query dialog in sample variant browser has a export type as CSV instead VCF

src/webcomponents/clinical/rga/rga-browser.js, src/webcomponents/clinical/rga/rga-gene-view.js, src/webcomponents/clinical/rga/rga-individual-family.js, src/webcomponents/clinical/rga/rga-individual-view.js, src/webcomponents/clinical/rga/rga-variant-individual.js, src/webcomponents/clinical/rga/rga-variant-view.js
This PR includes:
- fix on the attribute to check to assess the RGA index status of a study. KMDS-1395
- bugfixes for handling Cancer Studies that miss the family in Clinical Analysis. KMDS-1396 
- Remove "Possible CH" in all the table. KMDS-1378
- bugfix in pagination in Individual View. KMDS-1350
=> RGA bugfixes

src/webcomponents/commons/opencga-active-filters.js
This PR fixes the opencga-active-filters component to allow removing a filter when clicking on the counter badge element instead of in the filter button.
=> TASK-1952 - Not able to remove a filter when clicking on the counter badge

src/webcomponents/job/job-view.js
This PR fix displaying the job params in the `job-view` component.
=> TASK-1918 - Job overview view does not parse correctly the Input parameters for `analysis/variant/sample/stats/run` and leaves it as [object Object]

src/webcomponents/sample/sample-grid.js
This PR fixes an error in the sample browser when some samples do not have a `family.members` field.
=> TASK-1875 - IVA Sample browser shows a "Type error" when some attributes have  undefined values

src/webcomponents/commons/filters/catalog-distinct-autocomplete.js, src/webcomponents/commons/opencga-browser-filter.js, src/webcomponents/file/file-filter.js
This PR fixes filtering by disorders when the field `disorders.name` is empty.
=> TASK-2082 - Unable to filter by disorders when disorders.name is empty

src/webcomponents/variant/family-genotype-filter.js
This PR fixes selecting a mode of inheritance in the `family-genotype-filter` component.
=> TASK-2130 - Sample Genotypes filter is not applying Mode of Inheritance

src/webcomponents/commons/opencb-grid-toolbar.js, src/webcomponents/variant/interpretation/variant-interpreter-grid.js
This PR removes the Actions column from the columns dropdown and fixes the displayed title of the Population Frequencies column.
=> TASK-2151 - Actions column is still displayed in the grid of the Sample Variant Browser despite deselecting the Actions column

src/webcomponents/variant/interpretation/variant-interpreter-grid-formatter.js, src/webcomponents/variant/interpretation/variant-interpreter-grid.js
This PR disables the select and edit actions in the Sample Variant Browser when the interpretation is disabled.
=> TASK-2186 - Select and Edit actions should be disabled when the interpretation is locked

src/webcomponents/variant/analysis/sample-variant-stats-analysis.js
This PR adds a missing `indexId` field to the `sample-variant-stats-analysis` component.
=> TASK-2182 - Sample Variant Stats fail to create index due to the missing param indexId

src/webcomponents/commons/opencga-browser-filter.js, src/webcomponents/individual/individual-browser.js
This PR fixes the sex and karyotypic filters in individual browser.
=> TASK-2100 - Sex filter in Individual browser only accept uppercase MALE and FEMALE and fail to search other capitalizations

src/webcomponents/variant/interpretation/variant-interpreter-grid-formatter.js, src/webcomponents/variant/interpretation/variant-interpreter-grid.js
This PR fixes disabling evidences review actions (select and edit) when the interpretation is locked.
=> TASK-2233 - Locking an intrepretation does not lock the evidences review select and edit

src/core/utils-new.js, src/webcomponents/variant/interpretation/variant-interpreter-grid.js
This PR adds a new wrapper around Clipboard API for supporting non-secure contexts (HTTP).
=> TASK-2235 - Copy JSON feature doesn't work if users use HTTP URLs

src/webcomponents/file/file-grid.js
This PR fixes the exported columns of the TAB and the JSON fields in the `file-grid`.
=> TASK-2258 - File Browser- JSON and TSV format files generated using the Export feature show neither File IDs nor Sample IDs

src/webcomponents/variant/interpretation/variant-interpreter.js
This PR setting the right lock icon when a locked case is displayed
=> TASK-2266 - When an interpretation is locked a wrong Lock Image is displayed as if the case where locked

src/webcomponents/variant/interpretation/variant-interpreter-grid.js
This PR fixes a bug when a variant is unchecked in the `variant-interpreter-grid` component.
=> TASK-2187 - Deselecting a variant in the SVB resets the evidences selection

src/webcomponents/commons/filters/variant-file-info-filter.js
This PR fixes the generated fileData query in the `variant-file-info-filter` component.
=> TASK-3891 - Malformed fileData query when filtering variants in variant browser

package.json, src/sites/iva/conf/opencga-file-browser.settings.js, src/webcomponents/commons/opencga-browser-filter.js, src/webcomponents/file/file-browser.js, src/webcomponents/file/file-filter.js, src/webcomponents/file/file-grid.js, src/webcomponents/file/file-view.js
This PR fixes the query and visualisation of the Variant Index in File browser grid and view.
=> TASK-2444 - The Index column is displayed empty in the table of the File Browser

package.json, src/webcomponents/clinical/clinical-analysis-view.js, src/webcomponents/family/family-view.js
This PR updates the `family-view` and the `clinical-analysis-view` for using the new pedigree image returned in the family object.
=> TASK-1562 - Pedigree graph with a three-generation family fails to render properly in Family browser detailed tab

src/webcomponents/variant/variant-grid-formatter.js
This PR fixes the position of the tooltip displayed in the Population Frequencies column of Variant Browser.
=> TASK-4016 - Variant Browser - gnomAD exomes information out of window margin

src/webcomponents/variant/interpretation/variant-interpreter-grid-formatter.js
This PR fixes the cohort stats tooltip displayed in the variant interpreter grid.
=> TASK-4027 - Cohort Stats information displayed in the Sample Variant Browser table doesn't match with the information shown in the Details Tab

src/webcomponents/commons/filters/variant-file-info-filter.js
This PR fixes `variant-file-info-filter` component when the caller name or the file name has dots `.` characters.
=> TASK-4026 - Variant Caller File Filters shown in the Sample Variant Browser are not being recognised and passed to the query when selected

src/webcomponents/commons/opencga-update.js
This PR adds a new update customization in `opencga-update` for the `analyst.id` field of the interpretation.
=> TASK-4017 - Modifications are not saved when attempting to change the analyst of an already assigned interpretation

src/webcomponents/sample/sample-cancer-variant-stats-browser.js, src/webcomponents/sample/sample-cancer-variant-stats-plots.js
This PR fixes the default location filter in the `sample-cancer-variant-stats-browser` component.
=> TASK-729 - Display genomic location default filter

src/sites/iva/conf/opencga-variant-constants.js
This PR fixes a typo in the message displayed by the fullTextSearch field in the ClinVar section filter.
=> TASK-4030 - Incorrect information displayed in the tooltip of the Full-text search on HPO, ClinVar... filter"

src/sites/iva/conf/browsers.settings.js, src/webcomponents/variant/interpretation/variant-interpreter-methods.js, src/webcomponents/variant/interpretation/variant-interpreter.js
This PR allows to customize the available methods via configuration.
=> TASK-4753 - Implement RD Tiering Disable/Enable option by configuration. Not currently working.

src/webcomponents/variant/interpretation/variant-interpreter-browser-cancer.js, src/webcomponents/variant/interpretation/variant-interpreter-browser-cnv.js, src/webcomponents/variant/interpretation/variant-interpreter-browser-rd.js, src/webcomponents/variant/interpretation/variant-interpreter-browser-rearrangement.js
This PR locks file, fileData, and sampleData field in Sample Variant Browsers.
=> TASK-5494 - File, fileData and sample filters are not kept when applying a saved filter

src/webcomponents/clinical/clinical-analysis-create.js
This PR fixes the create clinical analysis config for the elements using the type "table", so now the tables a correctly visualised
=> PR - IVA Data-form - Clinical Analysis create table not visualised correctly
